spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservas_db
    username: user01
    password: reservas123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
    open-in-view: false

  sql:
    init:
      mode: embedded